Repository iansteyn/cosc-341-project, pull requests merged in 2024-12, with the labels that each got.

#31 Posts and PostListManager
  .idea/androidTestResultsUserPreferences.xml
  app/src/androidTest/java/com/example/cosc341_project/ExampleInstrumentedTest.java
  app/src/main/java/com/example/cosc341_project/MainActivity.java
  app/src/main/java/com/example/cosc341_project/data_classes/Comment.java
  app/src/main/java/com/example/cosc341_project/data_classes/Post.java
  app/src/main/java/com/example/cosc341_project/data_classes/PostListManager.java
  app/src/main/java/com/example/cosc341_project/data_classes/SightingPost.java
  app/src/main/java/com/example/cosc341_project/data_classes/User.java
  app/src/test/java/android/util/Log.java
  app/src/test/java/com/example/cosc341_project/ExampleUnitTest.java
  app/src/test/java/com/example/cosc341_project/data_classes/PostListManagerTest.java
  app/src/test/java/com/example/cosc341_project/data_classes/PostTest.java
Labels: documentation, chore

#35 Basic Map
  .idea/.name
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cosc341_project/ui/map/MapFragment.java
  app/src/main/res/layout/fragment_map.xml
  gradle/libs.versions.toml
Labels: feature

#40 Post feed
  app/build.gradle.kts
  app/src/main/java/com/example/cosc341_project/MainActivity.java
  app/src/main/java/com/example/cosc341_project/ui/feed/FeedFragment.java
  app/src/main/java/com/example/cosc341_project/ui/feed/FeedViewModel.java
  app/src/main/res/layout/comment_item.xml
  app/src/main/res/layout/discussion_post_item.xml
  app/src/main/res/layout/filter_view.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/post_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: feature

#41 User data management
  app/src/main/java/com/example/cosc341_project/data_classes/Post.java
  app/src/main/java/com/example/cosc341_project/data_classes/PostListManager.java
  app/src/main/java/com/example/cosc341_project/data_classes/SightingPost.java
  app/src/main/java/com/example/cosc341_project/data_classes/User.java
  app/src/main/java/com/example/cosc341_project/data_classes/UserList.java
  app/src/main/res/drawable/ic_dashboard_black_24dp.xml
  app/src/main/res/drawable/ic_notifications_black_24dp.xml
  app/src/main/res/drawable/icon_circle_plus_24dp.xml
  app/src/main/res/drawable/icon_home_24dp.xml
  app/src/main/res/drawable/icon_map_24dp.xml
  app/src/main/res/drawable/icon_person_24dp.xml
  app/src/main/res/drawable/img_alien.jpg
  app/src/main/res/drawable/img_big_salamander_baby.jpg
  app/src/main/res/drawable/img_bigfoot_blurry.jpg
  app/src/main/res/drawable/img_bigfoot_or_bear.webp
  app/src/main/res/drawable/img_lake_monster.webp
  app/src/main/res/drawable/img_ogopogo_green.jpg
  app/src/main/res/drawable/img_ogopogo_humps.jpg
  app/src/main/res/drawable/img_ogopogo_sturgeon.jpg
  app/src/main/res/drawable/img_shuswaggi.jpg
  app/src/main/res/drawable/pfp_aquafina.jpg
  app/src/main/res/drawable/pfp_bigfoot.jpg
  app/src/main/res/drawable/pfp_bill.png
  app/src/main/res/drawable/pfp_boy.png
  app/src/main/res/drawable/pfp_girl.png
  app/src/main/res/drawable/pfp_jeremy.png
  app/src/main/res/drawable/pfp_lakewoman.jpg
  app/src/main/res/drawable/pfp_mohamed.jpg
  app/src/main/res/drawable/pfp_mothman.png
  app/src/main/res/drawable/pfp_stop.jpg
  app/src/main/res/drawable/pfp_yomamma.png
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/test/java/com/example/cosc341_project/data_classes/PostTest.java
  app/src/test/java/com/example/cosc341_project/data_classes/UserListTest.java
Labels: documentation, chore

#49 Fixes for saving and adding posts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cosc341_project/data_classes/PostListManager.java
  app/src/main/java/com/example/cosc341_project/ui/feed/FeedFragment.java
  app/src/main/java/com/example/cosc341_project/ui/feed/FeedViewModel.java
  app/src/main/java/com/example/cosc341_project/ui/post/createPost.java
  app/src/test/java/com/example/cosc341_project/data_classes/PostListManagerTest.java
Labels: bug

#52 Post feed: Comments, sorting, reporting, general UI improvements
  app/src/main/java/com/example/cosc341_project/ui/feed/FeedFragment.java
  app/src/main/res/layout/comment_item.xml
  app/src/main/res/layout/discussion_post_item.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/post_item.xml
Labels: feature

#59 Profile bugfix
  app/src/main/java/com/example/cosc341_project/ui/post/createPost.java
  app/src/main/java/com/example/cosc341_project/ui/profile/ProfileFragment.java
Labels: bug

#56 Post changes
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/cosc341_project/ui/post/createPost.java
  app/src/main/res/layout/createpost.xml
  app/src/main/res/layout/fragment_post.xml
Labels: refactor

#55 Images
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/cosc341_project/data_classes/PostListManager.java
  app/src/main/java/com/example/cosc341_project/data_classes/SightingPost.java
  app/src/main/java/com/example/cosc341_project/data_classes/User.java
  app/src/main/java/com/example/cosc341_project/ui/feed/FeedFragment.java
  app/src/main/java/com/example/cosc341_project/ui/post/createPost.java
  app/src/main/res/drawable/img_alien.jpg
  app/src/main/res/drawable/img_big_salamander_baby.jpg
  app/src/main/res/drawable/img_bigfoot_blurry.jpg
  app/src/main/res/drawable/img_bigfoot_or_bear.png
  app/src/main/res/drawable/img_bigfoot_or_bear.webp
  app/src/main/res/drawable/img_from_camera.png
  app/src/main/res/drawable/img_lake_monster.png
  app/src/main/res/drawable/img_lake_monster.webp
  app/src/main/res/drawable/img_ogopogo_green.jpg
  app/src/main/res/drawable/img_ogopogo_humps.jpg
  app/src/main/res/drawable/img_ogopogo_sturgeon.jpg
  app/src/main/res/drawable/img_shuswaggi.jpg
  app/src/main/res/layout/image_gallery.xml
  app/src/main/res/layout/post_item.xml
Labels: feature

#50 feat(map-markers): add clickable markers for sighting posts on map
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/cosc341_project/data_classes/PostListManager.java
  app/src/main/java/com/example/cosc341_project/data_classes/SightingPost.java
  app/src/main/java/com/example/cosc341_project/ui/map/MapFragment.java
  app/src/main/java/com/example/cosc341_project/ui/post/createPost.java
  app/src/main/res/layout/activity_marker_info_popup.xml
  app/src/main/res/layout/filter_dialog.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/values/strings.xml
Labels: feature

#60 Profile user display
  app/src/main/java/com/example/cosc341_project/data_classes/UserList.java
  app/src/main/java/com/example/cosc341_project/ui/feed/FeedFragment.java
  app/src/main/java/com/example/cosc341_project/ui/profile/ProfileFragment.java
  app/src/main/res/layout/discussion_post_item.xml
  app/src/main/res/layout/filter_view.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/post_item.xml
  app/src/main/res/values/colors.xml
Labels: feature

#62 Feed touchup
  app/src/main/java/com/example/cosc341_project/ui/feed/FeedFragment.java
  app/src/main/java/com/example/cosc341_project/ui/map/MapFragment.java
  app/src/main/res/layout/fragment_profile.xml
Labels: bug

#63 Delete your own posts
  app/src/main/java/com/example/cosc341_project/ui/profile/ProfileFragment.java
  app/src/main/res/layout/profile_post_item.xml
Labels: feature

#64 Fixing Tags
  app/src/main/java/com/example/cosc341_project/ui/post/createPost.java
  app/src/main/res/drawable/placeholder_select_image.png
  app/src/main/res/layout/createpost.xml
Labels: bug, feature

#65 Spinner Markers Fix
  app/src/main/java/com/example/cosc341_project/data_classes/LocationList.java
  app/src/main/java/com/example/cosc341_project/ui/map/MapFragment.java
  app/src/main/java/com/example/cosc341_project/ui/post/createPost.java
  app/src/main/res/layout/activity_create_post.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature

#66 Fixed filter issue
  app/src/main/java/com/example/cosc341_project/ui/feed/FeedFragment.java
Labels: bug
